# Generated by Django 4.2 on 2023-07-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_orders", "0003_order_coupon_order_delivery_cost_order_discount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("Not Paid", "Не оплачен"), ("Paid", "Оплачен")],
                default="Not Paid",
                max_length=25,
                verbose_name="Статус заказа",
            ),
        ),
    ]
