# Generated by Django 4.2 on 2023-07-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_orders", "0004_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("Не оплачен", "Не оплачен"), ("Оплачен", "Оплачен")],
                default="Не оплачен",
                max_length=25,
                verbose_name="Статус заказа",
            ),
        ),
    ]
