# Generated by Django 4.2 on 2023-07-17 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="order",
        ),
    ]
