# Generated by Django 4.2 on 2023-07-12 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_catalog", "0001_initial"),
        ("app_cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartregistereduser",
            name="product_in_shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app_catalog.productinshop",
                verbose_name="Товары",
            ),
        ),
    ]
