# Generated by Django 4.2 on 2023-07-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_discounts", "0003_coupon"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coupon",
            options={"verbose_name": "Промокод", "verbose_name_plural": "Промокоды"},
        ),
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="Промокод"),
        ),
    ]
