FROM python:3.10

RUN mkdir /app
WORKDIR /app
COPY . /app/

RUN pip install --upgrade pip
RUN pip install -r requirements.txt


CMD [ "celery", "-A", "config", "worker", "-l", "info", "-f", "/var/log/worker.log" ]